name:                whisk
version:             0.1.0.0
github:              "alexoro412/whisk"
license:             BSD3
author:              "Alex Oro"
maintainer:          "alexoro412@gmail.com"
copyright:           "2018 Alex Oro"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexoro412/whisk#readme>

dependencies:
- base >= 4.7 && < 5
- stm 
- attoparsec 
- bytestring 
- hid
- mtl 
- containers 

library:
  source-dirs: src

executables:
  whisk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whisk

tests:
  whisk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whisk
